language: node_js
node_js:
- "stable"
services:
- postgresql
install: 
- npm install
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database wayfarer_db;' -U postgres
script: 
- npm test
after_success: 
- npm run test-coverage